import type { NextPage } from 'next';
import Head from 'next/head';
import GameContainer from '../components/GameContainer';
import { GetServerSideProps } from 'next';
import { PrismaClient, Character } from '@prisma/client';

type Props = {
  characters: Character[];
};

const Game: NextPage<Props> = ({ characters }) => {
  console.log(characters);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GameContainer characters={characters} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const prisma = new PrismaClient();
  const characters = await prisma.character.findMany({});
  return {
    props: { characters },
  };
};

export default Game;
